#!/bin/sh
cd "${0%/*}/../"
if [ $(uname) = "Darwin" ]; then
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -arch arm64 -arch x86_64; ./__getexecname_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -arch arm64 -arch x86_64; ./__getexecname_external;
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -arch arm64 -arch x86_64; ./__getbasepath_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -arch arm64 -arch x86_64; ./__getbasepath_external;
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -arch arm64 -arch x86_64; ./__getprogname_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -arch arm64 -arch x86_64; ./__getprogname_external;
elif [ $(uname) = "Linux" ]; then
  if [ -f "/bin/g++" ]; then
    g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_internal;
    g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_external;
    g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_internal;
    g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_external;
    g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_internal;
    g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_external;
  else
    clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall; ./__getexecname_internal;
    clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall; ./__getexecname_external;
    clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall; ./__getbasepath_internal;
    clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall; ./__getbasepath_external;
    clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall; ./__getprogname_internal;
    clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall; ./__getprogname_external;
  fi
elif [ $(uname) = "FreeBSD" ]; then
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static; ./__getexecname_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -static; ./__getexecname_external;
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static; ./__getbasepath_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -static; ./__getbasepath_external;
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static; ./__getprogname_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -static; ./__getprogname_external;
elif [ $(uname) = "DragonFly" ]; then
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_external;
elif [ $(uname) = "NetBSD" ]; then
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_external;
elif [ $(uname) = "OpenBSD" ]; then
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -lkvm -static; ./__getexecname_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -lkvm -static; ./__getexecname_external;
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -lkvm -static; ./__getbasepath_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -lkvm -static; ./__getbasepath_external;
  clang++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -lkvm -static; ./__getprogname_internal;
  clang++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -lkvm -static; ./__getprogname_external;
elif [ $(uname) = "SunOS" ]; then
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static-libgcc; ./__getexecname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -lproc -static-libgcc; ./__getexecname_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static-libgcc; ./__getbasepath_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -lproc -static-libgcc; ./__getbasepath_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static-libgcc; ./__getprogname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -lproc -static-libgcc; ./__getprogname_external;
elif [ $(uname) = "Haiku" ]; then
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_external;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_internal;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_external;
elif [ $(uname) = "QNX" ]; then
  q++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_internal;
  q++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getexecname_external;
  q++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_internal;
  q++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getbasepath_external;
  q++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_internal;
  q++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static; ./__getprogname_external;
else
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getexecname_internal.cpp -o __getexecname_internal.exe -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static -Wl,--subsystem,console; ./__getexecname_internal.exe;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getexecname_external.cpp -o __getexecname_external.exe -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static -Wl,--subsystem,console; ./__getexecname_external.exe;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getbasepath_internal.cpp -o __getbasepath_internal.exe -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static -Wl,--subsystem,console; ./__getbasepath_internal.exe;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getbasepath_external.cpp -o __getbasepath_external.exe -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static -Wl,--subsystem,console; ./__getbasepath_external.exe;
  g++ __getexecname/internal.cpp __getbasepath/internal.cpp __getprogname/internal.cpp example/__getprogname_internal.cpp -o __getprogname_internal.exe -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static -Wl,--subsystem,console; ./__getprogname_internal.exe;
  g++ __getexecname/external.cpp __getbasepath/external.cpp __getprogname/external.cpp example/__getprogname_external.cpp -o __getprogname_external.exe -I. -std=c++17 -Wall -static-libgcc -static-libstdc++ -static -Wl,--subsystem,console; ./__getprogname_external.exe;
fi
